// web/src/lib/plots/SignalPlot.svelte
<script>
   import { onMount } from 'svelte'
   import _ from 'lodash'
   import { COLORS, PLOT_HEIGHT, PLOT_MARGIN } from '../constants'
   import { signals, isPaused, measurements, rerenderPlot } from '../store'
   import dayjs from 'dayjs'
import { dataset_dev } from 'svelte/internal';

   export let name
   export let title
   let plot
   let uPlot
   let mounted = false

   onMount(async () => {
      const module = await import('uplot')
      uPlot = module.default
      mounted = true
      renderPlot()
   })

   function renderPlot() {
      if (!uPlot || !mounted) {
         return
      }

      if (plot) {
         plot.destroy()
      }

      const el = document.getElementById(`plot-${name}`)

      plot = new uPlot(
         {
            title,
            width: el.offsetWidth - PLOT_MARGIN,
            height: PLOT_HEIGHT,
            series: [
               {
                  label: 'Time',
                  value: (self, val) => dayjs(val).format('HH:mm:ss.SSS'),
                  // value: seriesTimestamp($timestamps[0]),
               },
               ..._.entries($measurements).map(([port, measurement], i) => {
                  return {
                     label: measurement.name,
                     stroke: COLORS[i],
                     value: (self, val) => val ? val.toExponential(6) : val,
                  }
               }),
            ],
            axes: [
               {
                  label: 'Time',
                  values: (self, vals) => vals.map((v) => dayjs(v).format('HH:mm:ss')),
                  // values: axesTimestamps($timestamps[0]),
               },
               {
                  label: title,
                  values: (self, vals) => vals.map((v) => v.toExponential(3)),
               },
            ],
            scales: {
               x: {
                  time: false,
               },
            },
         },
         undefined,
         el
      )
   }

   $: {
      $rerenderPlot
      rerenderPlot.set(false)
      renderPlot()
   }
   $: ($signals || $measurements) && setData()

   function setData() {
      if (!uPlot || !mounted || !plot) {
         return
      }

      const newData = []
      const prefix = {}
      const mValues = _.values($measurements)
      const time = _.unionBy(...mValues.map((x) => x.time))

      _.entries($measurements).map(([id, measurement]) => {
         const idx = measurement.time[0]
         if (!idx) {
            return
         }

         prefix[id] = _.fill(Array(time.indexOf(idx)), undefined)
      })

      _.entries($measurements).forEach(([id, measurement]) => {
         if ((measurement[name] || []).length > 2) {
            if (newData.length === 0) {
               newData.push(time)
            }

            newData.push(_.concat(prefix[id], measurement[name]))
         }
      })

      if (!$isPaused) {
         plot.setData(newData)
         // console.warn(newData[3])
      }
   }
</script>

<div id={`plot-${name}`} />

// web/src/components/SignalPlot.vue
<template>
  <UplotVue :data="data" :options="options" />
</template>

<script lang="ts">
import { defineComponent } from "@vue/runtime-core";
import _ from "lodash";
import uPlot, { Options } from "uplot";
import "uplot/dist/uPlot.min.css";
import dayjs from "dayjs";
import UplotVue from "./CustomUplot.vue";

interface Data {
  id: string;
  plot: uPlot | null;
  options: Options | null;
  data?: any
}

const COLORS = [
  "blue",
  "red",
  "green",
  "blueviolet",
  "brown",
  "darkcyan",
  "deepskyblue",
  "indigo",
  "chocolate",
  "crimson",
];

export default defineComponent({
  name: "SignalPlot",
  components: { UplotVue },
  props: {
    name: {
      type: String,
      required: true,
    },
    height: {
      type: Number,
      default: 200,
    },
    width: {
      type: Number,
      default: 200,
    },
  },
  data(): Data {
    return {
      id: "",
      plot: null,
      options: null
    }
  },
  created() {
    const device = this.$store.state.devices[0];
    const against = 0;
    this.id = "plot-" + _.uniqueId();
    this.options = {
      title: this.name,
      width: this.width,
      height: this.height,
      cursor: {
        drag: { x: true, y: true },
      },
      series: [
        {
          label: "Time",
          value: (self, value) => {
            return value;
          },
        },
        {
          label: device?.name,
          stroke: COLORS[0],
        },
        //   ...seriesDevices(state.devices),
      ],
      axes: [
        {
          label: "Time",
          values: (self: uPlot, values: number[]) => {
            const millisDiffer = values[values.length - 1] - against;
            let format = "ss.SSS";
            if (millisDiffer > 3600 * 1000) {
              format = "HH:mm";
            } else if (millisDiffer > 60 * 1000) {
              format = "mm:ss";
            }
            return values.map((value) =>
              dayjs.utc(value - against).format(format)
            );
          },
        },
        {
          label: this.name,
        },
      ],
      scales: {
        x: {
          time: false,
        },
      },
    };
  },
  beforeMount() {
    this.data = [[...new Array(100000)].map((_, i) => i), [...new Array(100000)].map((_, i) => i % 1000)];
  },
  mounted() {
    this.renderPlot();
  },
  methods: {
    renderPlot() {
      console.log("render plot");

      // find div with proper id
      const el = document.getElementById(this.id) as HTMLElement;
      const device = this.$store.state.devices[0];
      const against = 0;

      const opts: Options = {
        title: this.name,
        width: this.width - 50 || el.clientWidth - 15,
        height: this.height - 50,
        cursor: {
          drag: { x: true, y: true },
        },
        series: [
          {
            label: "Time",
            value: (self, value) => {
              return value;
            },
          },
          {
            label: device?.name,
            stroke: COLORS[0],
          },
          //   ...seriesDevices(state.devices),
        ],
        axes: [
          {
            label: "Time",
            values: (self: uPlot, values: number[]) => {
              const millisDiffer = values[values.length - 1] - against;
              let format = "ss.SSS";
              if (millisDiffer > 3600 * 1000) {
                format = "HH:mm";
              } else if (millisDiffer > 60 * 1000) {
                format = "mm:ss";
              }
              return values.map((value) =>
                dayjs.utc(value - against).format(format)
              );
            },
          },
          {
            label: this.name,
          },
        ],
        scales: {
          x: {
            time: false,
          },
        },
      };

      // if already present, destroy previous plot to prevent memory leaks
      if (this.plot) {
        this.plot.destroy();
      }

      // render new plot
      this.plot = new uPlot(opts, undefined, el);
      //   this.plot.
    },
  },
});
</script>
